<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>

		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>

		<ApplicationIcon>Pegasus.ico</ApplicationIcon>

		<!-- Versão -->
		<Version>1.0.0.2</Version>
		<AssemblyVersion>1.0.0.2</AssemblyVersion>
		<FileVersion>1.0.0.2</FileVersion>

		<!-- Publicação -->
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<PublishTrimmed>false</PublishTrimmed>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MySqlConnector" Version="2.4.0" />
	</ItemGroup>

</Project>